---
- name: Register if Keystore Exists
  stat:
    path: "{{keystore_path}}"
  register: keystore

- name: Register if Truststore Exists
  stat:
    path: "{{truststore_path}}"
  register: truststore

- name: Create Keystore and Truststore
  include_tasks: create_keystore_and_truststore.yml
  when: not keystore.stat.exists|bool or not truststore.stat.exists|bool or regenerate_keystore_and_truststore|bool

- set_fact:
    user: "{{zookeeper_user}}"
    group: "{{zookeeper_group}}"
  when: service_name == 'zookeeper'

- set_fact:
    user: "{{kafka_broker_user}}"
    group: "{{kafka_broker_group}}"
  when: service_name == 'kafka_broker'

- set_fact:
    user: "{{schema_registry_user}}"
    group: "{{schema_registry_group}}"
  when: service_name == 'schema_registry'

- set_fact:
    user: "{{kafka_rest_user}}"
    group: "{{kafka_rest_group}}"
  when: service_name == 'kafka_rest'

- set_fact:
    user: "{{kafka_connect_user}}"
    group: "{{kafka_connect_group}}"
  when: service_name == 'kafka_connect'

- set_fact:
    user: "{{ksql_user}}"
    group: "{{ksql_group}}"
  when: service_name == 'ksql'

- set_fact:
    user: "{{control_center_user}}"
    group: "{{control_center_group}}"
  when: service_name == 'control_center'

- name: Set Truststore and Keystore File Permissions
  file:
    path: "{{item}}"
    owner: "{{user}}"
    group: "{{group}}"
    mode: '0644'
  loop:
    - "{{keystore_path}}"
    - "{{truststore_path}}"
    - "{{ca_cert_path}}"
    - "{{cert_path}}"
    - "{{key_path}}"
